# render.yaml — PrepArena deployment (API + Extractor)
services:
  - type: web
    name: preparena-api
    env: node
    rootDir: server
    plan: starter
    buildCommand: "npm ci && npm run render-build"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: "/api/health"
    disk:
      name: uploads-disk
      mountPath: /data/uploads
      sizeGB: 10
    envVars:
      - key: NODE_ENV
        value: production
      # Use the var name your code already supports
      - key: MONGO_URI
        value: ""          # <-- fill in on Render after first deploy (or commit it if you must)
      # Optional redundancy; your code already reads both names
      - key: MONGODB_URI
        value: ""          # can leave empty or same value as MONGO_URI
      - key: JWT_SECRET
        value: ""          # set on Render
      # AWS S3 Configuration (Required for persistent file storage)
      - key: AWS_ACCESS_KEY_ID
        value: ""          # set on Render
      - key: AWS_SECRET_ACCESS_KEY
        value: ""          # set on Render  
      - key: AWS_REGION
        value: "us-east-1"
      - key: AWS_S3_BUCKET
        value: "preparena-uploads"  # or your bucket name
      - key: UPLOAD_DIR
        value: /data/uploads  # fallback for local storage
      - key: CORS_ORIGINS
        value: "https://preparena.vercel.app,https://*.vercel.app,https://preparena.in"
      - key: EXTRACTOR_URL
        value: "https://preparena-extractor.onrender.com"  # replace with your extractor URL
      - key: EXTRACTOR_AUTH_TOKEN
        value: "dev-extractor-token"                       # set/empty to match extractor

  - type: web
    name: preparena-extractor
    env: python
    rootDir: .
    plan: starter
    buildCommand: "pip install -r scripts/requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT scripts.extractor_wsgi:app"
    autoDeploy: true
    healthCheckPath: "/healthz"
    disk:
      name: extractor-work
      mountPath: /data
      sizeGB: 2
    envVars:
      - key: WORK_DIR
        value: /data/work
      - key: MAX_CONTENT_LENGTH_MB
        value: "20"
      - key: AUTH_TOKEN
        value: "dev-extractor-token"   # or "" if you don't want auth
